import { User, Contact, Campaign, ActivityLog } from './types';

export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'Jordan Pierce', email: 'jordan@2bitscreative.com', role: 'admin' },
  { id: 'u2', name: 'Teagan Reyes', email: 'teagan@2bitscreative.com', role: 'internal' },
  { id: 'u3', name: 'Marcus Webb', email: 'marcus@2bitscreative.com', role: 'internal' },
  { id: 'u4', name: 'Darius Cole', email: 'darius@athlete.com', role: 'client_athlete', clientId: 'c1' },
  { id: 'u5', name: 'Summit Energy', email: 'marketing@summitenergy.com', role: 'client_brand', clientId: 'c4' },
];

export const MOCK_CONTACTS: Contact[] = [
  {
    id: 'c1',
    type: 'athlete',
    name: 'Darius Cole',
    sport: 'Basketball',
    school: 'University of Texas',
    league: 'NCAA',
    email: 'darius@athlete.com',
    phone: '512-555-0101',
    socialHandles: [
      { platform: 'Instagram', handle: '@dcole_hoops' },
      { platform: 'TikTok', handle: '@dariuscole' },
      { platform: 'Twitter', handle: '@DCole_UT' },
    ],
    dealHistory: [
      { id: 'd1', title: 'Summit Energy NIL Deal', value: 25000, stage: 'active', startDate: '2026-01-01', endDate: '2026-12-31' },
    ],
    notes: 'Top-ranked PG. 280k IG followers. Very engaged audience, brand-safe. Game day content performs best.',
    tags: ['basketball', 'nil', 'high-value', 'ncaa'],
    stage: 'active',
    dealValue: 25000,
    createdAt: '2025-09-01',
    updatedAt: '2026-05-15',
  },
  {
    id: 'c2',
    type: 'athlete',
    name: 'Mia Torres',
    sport: 'Soccer',
    school: 'UCLA',
    league: 'NCAA / NWSL',
    email: 'mia@athlete.com',
    phone: '310-555-0202',
    socialHandles: [
      { platform: 'Instagram', handle: '@mia_torres10' },
      { platform: 'TikTok', handle: '@miatorreskicks' },
    ],
    dealHistory: [
      { id: 'd2', title: 'Nike Apparel Campaign', value: 18000, stage: 'completed', startDate: '2025-08-01', endDate: '2026-01-31' },
      { id: 'd3', title: 'GatorSport Q2 Activation', value: 12000, stage: 'in_talks', startDate: '2026-06-01' },
    ],
    notes: 'Rising star. Strong female athlete brand. Best for lifestyle + apparel content.',
    tags: ['soccer', 'nil', 'lifestyle', 'womens-sports'],
    stage: 'in_talks',
    dealValue: 30000,
    createdAt: '2025-07-15',
    updatedAt: '2026-06-01',
  },
  {
    id: 'c3',
    type: 'athlete',
    name: 'Khalil James',
    sport: 'Football',
    school: 'Ohio State',
    league: 'NCAA',
    email: 'khalil@athlete.com',
    phone: '614-555-0303',
    socialHandles: [
      { platform: 'Instagram', handle: '@kjames_osu' },
      { platform: 'Twitter', handle: '@KhalilJames_OSU' },
    ],
    dealHistory: [],
    notes: 'Incoming freshman. Projected starter. Early outreach — great pipeline candidate.',
    tags: ['football', 'prospect', 'high-value', 'ncaa'],
    stage: 'lead',
    dealValue: 0,
    createdAt: '2026-04-10',
    updatedAt: '2026-06-10',
  },
  {
    id: 'c4',
    type: 'brand',
    name: 'Summit Energy',
    email: 'marketing@summitenergy.com',
    phone: '737-555-0404',
    socialHandles: [
      { platform: 'Instagram', handle: '@summitenergy' },
    ],
    dealHistory: [
      { id: 'd4', title: 'Darius Cole NIL Activation', value: 25000, stage: 'active', startDate: '2026-01-01', endDate: '2026-12-31' },
    ],
    notes: 'Energy drink brand. Target demo: 18-24 male athletes. Approves fast, good communicator.',
    tags: ['beverage', 'energy', 'sponsor', 'nil'],
    stage: 'active',
    dealValue: 25000,
    createdAt: '2025-11-20',
    updatedAt: '2026-06-01',
  },
  {
    id: 'c5',
    type: 'brand',
    name: 'GatorSport Nutrition',
    email: 'partnerships@gatorsport.com',
    phone: '407-555-0505',
    socialHandles: [],
    dealHistory: [
      { id: 'd5', title: 'Mia Torres Q2 Sponsorship', value: 12000, stage: 'in_talks', startDate: '2026-06-01' },
    ],
    notes: 'Sports nutrition. Deal in negotiation. Responsive contact: Dana Li.',
    tags: ['nutrition', 'supplement', 'womens-sports'],
    stage: 'in_talks',
    dealValue: 12000,
    createdAt: '2026-03-05',
    updatedAt: '2026-06-12',
  },
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp1',
    title: 'Summit Energy x Darius Cole — Season Campaign',
    type: 'nil_deal',
    clientIds: ['c1', 'c4'],
    clientNames: ['Darius Cole', 'Summit Energy'],
    status: 'active',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    description: 'Full-year NIL partnership. Game-day content, product integrations, and social amplification across IG + TikTok.',
    tags: ['basketball', 'nil', 'season-long'],
    dealValue: 25000,
    kpis: [
      { label: 'Total Reach', value: '2.4M', trend: 'up' },
      { label: 'Avg Engagement Rate', value: '6.2%', trend: 'up' },
      { label: 'Deliverables Completed', value: '8/12', trend: 'flat' },
      { label: 'Timeline Adherence', value: '92%', trend: 'up' },
    ],
    deliverables: [
      {
        id: 'del1',
        campaignId: 'camp1',
        title: 'Game Night IG Reel — March',
        type: 'video',
        status: 'in_review',
        assigneeName: 'Marcus Webb',
        dueDate: '2026-06-20',
        fileUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        thumbnailUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400',
        comments: [
          {
            id: 'com1',
            deliverableId: 'del1',
            userId: 'u2',
            userName: 'Teagan Reyes',
            userRole: 'internal',
            body: 'Color grade on the court shots looks a bit cool — can we warm it up to match Summit brand palette?',
            resolved: false,
            timestamp: 12.5,
            createdAt: '2026-06-14T10:30:00Z',
            replies: [],
          },
          {
            id: 'com2',
            deliverableId: 'del1',
            userId: 'u3',
            userName: 'Marcus Webb',
            userRole: 'internal',
            body: 'Cut feels tight at 0:08 — the dribble sequence gets choppy. Extending by 2 frames should fix it.',
            resolved: true,
            timestamp: 8.0,
            createdAt: '2026-06-14T11:00:00Z',
            replies: [
              { id: 'r1', userId: 'u3', userName: 'Marcus Webb', body: 'Fixed in v2 export — uploading now.', createdAt: '2026-06-15T09:00:00Z' },
            ],
          },
          {
            id: 'com3',
            deliverableId: 'del1',
            userId: 'u4',
            userName: 'Darius Cole',
            userRole: 'client_athlete',
            body: 'Love this! Can we make the Summit logo entrance a little smoother at the end?',
            resolved: false,
            timestamp: 28.0,
            createdAt: '2026-06-15T14:00:00Z',
            replies: [],
          },
        ],
        createdAt: '2026-06-01',
      },
      {
        id: 'del2',
        campaignId: 'camp1',
        title: 'Summit x Darius — Brand Kit Static',
        type: 'graphic',
        status: 'in_review',
        assigneeName: 'Teagan Reyes',
        dueDate: '2026-06-22',
        fileUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=1200&h=800',
        thumbnailUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400',
        comments: [
          {
            id: 'com4',
            deliverableId: 'del2',
            userId: 'u1',
            userName: 'Jordan Pierce',
            userRole: 'admin',
            body: 'Logo lockup needs more breathing room — bump the padding on the right side.',
            resolved: false,
            pinX: 68,
            pinY: 25,
            createdAt: '2026-06-15T09:00:00Z',
            replies: [],
          },
          {
            id: 'com5',
            deliverableId: 'del2',
            userId: 'u2',
            userName: 'Teagan Reyes',
            userRole: 'internal',
            body: 'Headline font weight — should be ExtraBold per brand guide, currently looks like Bold.',
            resolved: false,
            pinX: 30,
            pinY: 55,
            createdAt: '2026-06-15T10:15:00Z',
            replies: [],
          },
        ],
        createdAt: '2026-06-05',
      },
      {
        id: 'del3',
        campaignId: 'camp1',
        title: 'Pre-Game Story Series (x3)',
        type: 'graphic',
        status: 'approved',
        assigneeName: 'Teagan Reyes',
        dueDate: '2026-06-10',
        thumbnailUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
        comments: [],
        createdAt: '2026-05-20',
      },
      {
        id: 'del4',
        campaignId: 'camp1',
        title: 'TikTok Integration — Product Sip Scene',
        type: 'video',
        status: 'todo',
        assigneeName: 'Marcus Webb',
        dueDate: '2026-07-05',
        comments: [],
        createdAt: '2026-06-10',
      },
    ],
    createdAt: '2025-12-15',
  },
  {
    id: 'camp2',
    title: 'Mia Torres — Nike Game Day Series',
    type: 'game_day',
    clientIds: ['c2'],
    clientNames: ['Mia Torres'],
    status: 'completed',
    startDate: '2025-08-01',
    endDate: '2026-01-31',
    tags: ['soccer', 'nike', 'game-day'],
    dealValue: 18000,
    kpis: [
      { label: 'Total Reach', value: '1.1M', trend: 'up' },
      { label: 'Avg Engagement Rate', value: '8.1%', trend: 'up' },
      { label: 'Deliverables Completed', value: '6/6', trend: 'up' },
      { label: 'Timeline Adherence', value: '100%', trend: 'up' },
    ],
    deliverables: [],
    createdAt: '2025-07-20',
  },
  {
    id: 'camp3',
    title: 'GatorSport x Mia Torres — Q3 Activation',
    type: 'sponsorship',
    clientIds: ['c2', 'c5'],
    clientNames: ['Mia Torres', 'GatorSport Nutrition'],
    status: 'planning',
    startDate: '2026-07-01',
    endDate: '2026-09-30',
    tags: ['soccer', 'nutrition', 'q3'],
    dealValue: 12000,
    kpis: [],
    deliverables: [
      {
        id: 'del5',
        campaignId: 'camp3',
        title: 'Campaign Brief Deck',
        type: 'graphic',
        status: 'in_progress',
        assigneeName: 'Jordan Pierce',
        dueDate: '2026-06-25',
        comments: [],
        createdAt: '2026-06-12',
      },
    ],
    createdAt: '2026-06-01',
  },
];

export const MOCK_ACTIVITY: ActivityLog[] = [
  { id: 'a1', contactId: 'c1', type: 'call', summary: 'Intro call — discussed Season 2026 deliverable schedule.', date: '2026-06-10T14:00:00Z', userId: 'u1', userName: 'Jordan Pierce' },
  { id: 'a2', contactId: 'c1', type: 'email', summary: 'Sent Q2 campaign report to Darius & Summit reps.', date: '2026-06-08T10:00:00Z', userId: 'u3', userName: 'Marcus Webb' },
  { id: 'a3', contactId: 'c4', type: 'meeting', summary: 'Mid-year check-in with Summit marketing team. Positive on renewal.', date: '2026-06-05T11:00:00Z', userId: 'u1', userName: 'Jordan Pierce' },
  { id: 'a4', contactId: 'c2', type: 'email', summary: 'GatorSport contract draft sent for review.', date: '2026-06-12T09:30:00Z', userId: 'u1', userName: 'Jordan Pierce' },
  { id: 'a5', contactId: 'c3', type: 'note', summary: 'Khalil listed in OSU depth chart as Day 1 starter. Accelerate outreach.', date: '2026-06-13T16:00:00Z', userId: 'u3', userName: 'Marcus Webb' },
];

export const SESSION_OPTIONS = [
  { user: MOCK_USERS[0], label: 'Admin — Jordan Pierce', description: 'Full access: all clients, campaigns, settings' },
  { user: MOCK_USERS[1], label: 'Internal — Teagan Reyes (Designer)', description: 'Internal dashboard, content review' },
  { user: MOCK_USERS[3], label: 'Client — Darius Cole (Athlete)', description: 'Restricted: own campaigns only' },
  { user: MOCK_USERS[4], label: 'Client — Summit Energy (Brand)', description: 'Restricted: own campaigns only' },
];
